services:
  - type: web
    name: tcet-attendance-management-system
    env: node
    plan: free
    buildCommand: npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        value: mongodb+srv://hiteshsutharvfx_db_user:5O2u6aMsbtcrHXnf@cluster0.eaa6hyq.mongodb.net/attendance_system?retryWrites=true&w=majority&appName=Cluster0
      - key: JWT_SECRET
        value: super_secret_jwt_key_tcet_attendance_2026_production_secure_token
      - key: MASTER_RESET_PASSWORD
        value: RESET@2026
